import { configureLocalization } from '@lit/localize';
import { sourceLocale, targetLocales } from './generated/locale-codes.js';

// Import locales generated by lit-localize
import * as enLocale from './generated/locales/en.js';
import * as esLocale from './generated/locales/es.js';

const localizedTemplates = new Map([
  ['en', enLocale],
  ['es', esLocale],
]);

export const { getLocale, setLocale } = configureLocalization({
  sourceLocale,
  targetLocales,
  loadLocale: async (locale) => {
    return localizedTemplates.get(locale);
  },
});

// Fungsi pembungkus untuk menyimpan ke localStorage
export const changeLocale = async (newLocale) => {
  console.log(`Changing locale to: ${newLocale}`);
  try {
    await setLocale(newLocale);
    localStorage.setItem('locale', newLocale);
    console.log(`Locale successfully changed to: ${getLocale()}`);
  } catch (e) {
    console.error(`Failed to change locale to ${newLocale}:`, e);
  }
};

// Inisialisasi bahasa dari localStorage saat pertama kali dimuat
const savedLocale = localStorage.getItem('locale');
if (savedLocale && savedLocale !== getLocale()) {
  setLocale(savedLocale);
}
