import { configureLocalization } from '@lit/localize';
import { sourceLocale, targetLocales } from './generated/locale-codes.js';

// Import locales generated by lit-localize
import * as enLocale from './generated/locales/en.js';
import * as esLocale from './generated/locales/es.js';

const localizedTemplates = new Map([
  ['en', enLocale.templates],
  ['es', esLocale.templates],
]);

export const { getLocale, setLocale } = configureLocalization({
  sourceLocale,
  targetLocales,
  loadLocale: (locale) => {
    return Promise.resolve(localizedTemplates.get(locale));
  },
});
